server:
   servlet:
      context-path: /auth
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      hibernate:
        type: trace