server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/loiclude?createDatabaseIfNotExist=true
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
eureka:
   instance:
      prefer-ip-address: false
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://registry-service:8761/eureka/
security:
   oauth2:
      resource:
         user-info-uri: http://api-gateway:8080/auth/user/current
         token-info-uri: http://api-gateway:8080/auth/oauth/check_token
