server:
  port: 8761 #the default port used for eureka servers
management:
  endpoints:
    exposure:
      include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    prefer-ip-address: true #when the application registers with eureka, it uses its IP address rather than its hostname
  client:
    register-with-eureka: false #tells the built-in eureka client to not register itself with eureka, because we should act as a server
    fetch-registry: false