server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      connection-timeout: 30000
      jdbc-url: jdbc:mysql://mysql:3306/loiclude
      password: admin123
      maximum-pool-size: 30
      idle-timeout: 600000
      max-lifetime: 1800000
      username: root
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry-service:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
security:
  oauth2:
    client:
      clientId: product-service
      clientSecret: admin
      grant-type: client_credentials
      scope: server
      user-authorization-uri: http://api-gateway:8080/auth/oauth/authorize
      access-token-uri: http://api-gateway:8080/auth/oauth/token
    resource:
      user-info-uri: http://api-gateway:8080/auth/user/current
      token-info-uri: http://api-gateway:8080/auth/oauth/check_token